//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATIONS
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string CODE_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int SORT_ID { get; set; }
        public string RESOURCE_LEVEL { get; set; }
        public int CHILDREN_COUNT { get; set; }
        public string ADD_SUBAPP { get; set; }
        public string USE_SCOPE { get; set; }
        public Nullable<int> INHERITED_STATE { get; set; }
        public System.DateTime MODIFY_TIME { get; set; }
        public string URL1 { get; set; }
        public string URL2 { get; set; }
        public string URL3 { get; set; }
        public string MENU { get; set; }
        public string PARA1 { get; set; }
        public string PARA2 { get; set; }
        public string TARGET { get; set; }
        public string DEVICE { get; set; }
        public string DEVICETYPE { get; set; }
        public string WORKTYPE { get; set; }
        public string SelectType { get; set; }
    }
}
