//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ApplyInfo
    {
        public string ApplyID { get; set; }
        public string ApplyCode { get; set; }
        public Nullable<int> ApplyType { get; set; }
        public string ApplyUserName { get; set; }
        public string ApplyUserID { get; set; }
        public string LeaveType { get; set; }
        public string ExtWorkType { get; set; }
        public string Vehicle { get; set; }
        public Nullable<int> BusinessType { get; set; }
        public string StartCity { get; set; }
        public string DestinationCity { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string SuppleTime { get; set; }
        public Nullable<int> SuppleType { get; set; }
        public Nullable<double> ApplyDays { get; set; }
        public string ApplyReason { get; set; }
        public Nullable<int> Status { get; set; }
        public string TogetherIDs { get; set; }
        public string TogetherNames { get; set; }
        public string InputUserID { get; set; }
        public string InputUserName { get; set; }
        public string InputUserDepID { get; set; }
        public string InputUserDepName { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string LastModifyUserID { get; set; }
        public string LastModifyUserName { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public string ExtWorkIsOut { get; set; }
    }
}
