//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Check
    {
        public string CheckID { get; set; }
        public string CheckUserID { get; set; }
        public string CheckUserName { get; set; }
        public string CheckDepID { get; set; }
        public string CheckDepName { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> CheckType { get; set; }
        public string InputUserID { get; set; }
        public string InputUserName { get; set; }
        public string InputDate { get; set; }
    }
}
