//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_WeChatBind
    {
        public string GUID { get; set; }
        public string BindID { get; set; }
        public string OpenID { get; set; }
        public Nullable<System.DateTime> BindDate { get; set; }
        public Nullable<System.DateTime> UnBindDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> LoginTimes { get; set; }
    }
}
