//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KQ_KqData
    {
        public string GUID { get; set; }
        public string EmpSysID { get; set; }
        public Nullable<System.DateTime> KqDate { get; set; }
        public Nullable<int> KqTime { get; set; }
        public string IsKeyin { get; set; }
        public string IsKouKuan { get; set; }
        public string Remark { get; set; }
        public string ResultMark { get; set; }
        public string IsModified { get; set; }
        public Nullable<short> DevID { get; set; }
        public string KeyinOprtNo { get; set; }
        public Nullable<System.DateTime> KeyinDay { get; set; }
        public string LotNoGUID { get; set; }
        public Nullable<long> CardID { get; set; }
        public Nullable<byte> ReaderID { get; set; }
        public string IsInvalid { get; set; }
        public Nullable<System.DateTime> kqdatetime { get; set; }
        public string cardsn { get; set; }
        public string phototime { get; set; }
        public Nullable<int> isok { get; set; }
        public string svrip { get; set; }
        public string devip { get; set; }
        public byte[] cardphoto { get; set; }
    }
}
