//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KQ_OtType
    {
        public string OtTypeSysID { get; set; }
        public string OtTypeNo { get; set; }
        public string OtTypeName { get; set; }
        public string OtIsOffSet { get; set; }
        public string OtIsDefault { get; set; }
        public string CalcItemEExpr { get; set; }
        public string CalcItemCExpr { get; set; }
    }
}
