//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HR_ConstructionEntities : DbContext
    {
        public HR_ConstructionEntities()
            : base("name=HR_ConstructionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPLICATIONS> APPLICATIONS { get; set; }
        public virtual DbSet<FUNCTIONS> FUNCTIONS { get; set; }
        public virtual DbSet<HR_Check> HR_Check { get; set; }
        public virtual DbSet<MATERIAL> MATERIAL { get; set; }
        public virtual DbSet<ORGANIZATIONS> ORGANIZATIONS { get; set; }
        public virtual DbSet<OU_USERS> OU_USERS { get; set; }
        public virtual DbSet<ROLE_TO_FUNCTIONS> ROLE_TO_FUNCTIONS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<HR_WeChatBind> HR_WeChatBind { get; set; }
        public virtual DbSet<EXPRESSIONS> EXPRESSIONS { get; set; }
        public virtual DbSet<TASK_LIST_VIEW> TASK_LIST_VIEW { get; set; }
        public virtual DbSet<SYS_DICTIONARY> SYS_DICTIONARY { get; set; }
        public virtual DbSet<KQ_DayoffType> KQ_DayoffType { get; set; }
        public virtual DbSet<KQ_OtType> KQ_OtType { get; set; }
        public virtual DbSet<HR_ApplyInfo> HR_ApplyInfo { get; set; }
        public virtual DbSet<KQ_KqData> KQ_KqData { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<GROUP_USERS> GROUP_USERS { get; set; }
        public virtual DbSet<GROUPS> GROUPS { get; set; }
    }
}
