//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public string ID { get; set; }
        public string APPLICATION_NAME { get; set; }
        public string PROGRAM_NAME { get; set; }
        public string RESOURCE_ID { get; set; }
        public int SORT_ID { get; set; }
        public string CLASS { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> PAGE_QUANTITY { get; set; }
        public string FILE_PATH { get; set; }
        public string ORIGINAL_NAME { get; set; }
        public string CREATOR { get; set; }
        public string LAST_UPLOAD_TAG { get; set; }
        public Nullable<System.DateTime> CREATE_DATETIME { get; set; }
        public string CHECKOUT_USER { get; set; }
        public Nullable<System.DateTime> CHECKOUT_TIME { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_TIME { get; set; }
        public string EXTRA_DATA { get; set; }
    }
}
