//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATIONS
    {
        public string GUID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string OBJ_NAME { get; set; }
        public string PARENT_GUID { get; set; }
        public string RANK_CODE { get; set; }
        public string INNER_SORT { get; set; }
        public string ORIGINAL_SORT { get; set; }
        public string GLOBAL_SORT { get; set; }
        public string ALL_PATH_NAME { get; set; }
        public int ORG_CLASS { get; set; }
        public int ORG_TYPE { get; set; }
        public int CHILDREN_COUNTER { get; set; }
        public int STATUS { get; set; }
        public string CUSTOMS_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime MODIFY_TIME { get; set; }
        public string SYSDISTINCT1 { get; set; }
        public string SYSDISTINCT2 { get; set; }
        public string SYSCONTENT1 { get; set; }
        public string SYSCONTENT2 { get; set; }
        public string SYSCONTENT3 { get; set; }
    }
}
