//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DICTIONARY
    {
        public string ItemID { get; set; }
        public string ParentID { get; set; }
        public string ItemTypeID { get; set; }
        public string ItemText { get; set; }
        public string ItemValue { get; set; }
        public string ItemAttribute1 { get; set; }
        public string ItemAttribute2 { get; set; }
        public string ItemAttribute3 { get; set; }
        public string ItemAttribute4 { get; set; }
        public string ItemAttribute5 { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SortID { get; set; }
        public byte State { get; set; }
        public string UID { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<int> OperateVer { get; set; }
    }
}
