//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_LIST_VIEW
    {
        public System.Guid TaskID { get; set; }
        public Nullable<int> SORT_ID { get; set; }
        public string APPLICATION_NAME { get; set; }
        public string PROGRAM_NAME { get; set; }
        public string RESOURCE_ID { get; set; }
        public string TASK_TITLE { get; set; }
        public string LEVEL { get; set; }
        public string SOURCE { get; set; }
        public string SOURCE_NAME { get; set; }
        public string SOURCE_LOGON_NAME { get; set; }
        public string DESTINATION { get; set; }
        public string DESTINATION_NAME { get; set; }
        public string DESTINATION_LOGON_NAME { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> READ_TIME { get; set; }
        public string EMERGENCY { get; set; }
        public string PURPOSE { get; set; }
        public Nullable<System.DateTime> EXPIRE_TIME { get; set; }
        public Nullable<System.DateTime> DELIVER_TIME { get; set; }
        public string STATUS { get; set; }
        public string BODY { get; set; }
        public Nullable<int> DealState { get; set; }
        public string TaskType { get; set; }
        public string Remind { get; set; }
    }
}
