//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public string GUID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string LOGON_NAME { get; set; }
        public string IC_CARD { get; set; }
        public string PWD_TYPE_GUID { get; set; }
        public string USER_PWD { get; set; }
        public string RANK_CODE { get; set; }
        public string E_MAIL { get; set; }
        public int POSTURAL { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime MODIFY_TIME { get; set; }
        public int AD_COUNT { get; set; }
        public string PERSON_ID { get; set; }
        public string SYSDISTINCT1 { get; set; }
        public string SYSDISTINCT2 { get; set; }
        public string SYSCONTENT1 { get; set; }
        public string SYSCONTENT2 { get; set; }
        public string SYSCONTENT3 { get; set; }
        public string OLD_NAME { get; set; }
        public Nullable<int> SEX { get; set; }
        public Nullable<int> NATION { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<int> DUTY { get; set; }
        public Nullable<int> USERTYPER { get; set; }
        public string NATIVEPLACE { get; set; }
        public string BIRTHADDR { get; set; }
        public string REGADDR { get; set; }
        public string LOVE { get; set; }
        public Nullable<int> STU_EXP { get; set; }
        public Nullable<int> DEGREE { get; set; }
        public string SCHOOL { get; set; }
        public string PROFESSION { get; set; }
        public string GRADUATETIME { get; set; }
        public string CARDID { get; set; }
        public string EMAIL { get; set; }
        public string OFTEL { get; set; }
        public string FAMTEL { get; set; }
        public string MOBILE { get; set; }
        public string VIRTEL { get; set; }
        public Nullable<int> POLFEA { get; set; }
        public string JOINPARTYTIME { get; set; }
        public string JOINPARTYINTODUCER { get; set; }
        public Nullable<System.DateTime> JOINCOMTIME { get; set; }
        public Nullable<System.DateTime> CONTRACTTIME { get; set; }
        public Nullable<System.DateTime> CONTRACTTLEN { get; set; }
        public string ATTENDWORKTIME { get; set; }
        public string PhotoImg { get; set; }
        public string SMSID { get; set; }
        public string AcdNo { get; set; }
        public string SalaryNo { get; set; }
        public Nullable<System.DateTime> DisnDate { get; set; }
        public Nullable<int> DisnCondition { get; set; }
        public string DisnMemo { get; set; }
        public string EmName { get; set; }
        public string EmDomain { get; set; }
        public string SmtpServer { get; set; }
        public Nullable<int> HughDay { get; set; }
        public int IsMarry { get; set; }
        public Nullable<int> AGE { get; set; }
        public string OFVIRTEL { get; set; }
        public string EmergencyTel { get; set; }
        public string EmergencyContact { get; set; }
        public Nullable<int> Registered { get; set; }
        public string QQ { get; set; }
        public string WeChatOpenID { get; set; }
        public string DDOpenID { get; set; }
        public string DDUserID { get; set; }
        public string ValidJson { get; set; }
    }
}
