//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System; 
    
    public partial class WFSubmit
    { 
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string ResourceID { get; set; }
        public string ProcessInstanceID { get; set; }
        public string ActivityInstanceID { get; set; }
        public string WorkItemID { get; set; }
        public Boolean IsWithdraw { get; set; }

        public Boolean IsProcessInstanceEnd { get; set; }
        public Boolean IsExitNode { get; set; }

        public string Opinion { get; set; }

        public string AppendOpinion { get; set; }
        public string ProcessDinfineKey { get; set; }
        public string ActivityDCode { get; set; }
        public string AppName { get; set; }
        public int AutoSendFeedback { get; set; }
        public string DepID { get; set; }
        public string UserFullPath { get; set; }

        public string ActivityName { get; set; }
        public string TaskSubject { get; set; }
        public string TaskUrl { get; set; } 
        public object Activities { get; set; }
        public object WFRelativeDatas { get; set; }  
    }
}
